name: postgres

on: [push]

  jobs:
    build:
      runs-on: ubuntu:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRESPASSWORD: postgres
        ports:
          - 5432:5432
        volumes:
            - .:.
           