name: postgres

on: [push]
jobs:
  build:
    runs-on: ubuntu:latest
      services:
        postgres:
          image: postgres
          env:
            POSTGRESPASSWORD: postgres
          ports:
            - 5432:5432
          volumes:
              - .:.
           