name: Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        uses: ./.github/action-check
      - name: Build
        uses: ./.github/action-build
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ./.github/action-deploy
        with:
          args: "staging"
  deploy-production:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ./.github/action-deploy
        with:
          args: "production"